apiVersion: v1
kind: Service
metadata:
  name: nodejs-image
spec:
  selector:
    app: nodejs-image
  ports:
    - protocol: TCP
      port: 5000       # Exposed service port
      targetPort: 5000 # Matches containerPort in Deployment
  type: ClusterIP

  