apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-image
  template:
    metadata:
      labels:
        app: nodejs-image
    spec:
      containers:
        - name: nodejs-container
          image: journal-nodejs-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

      