apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejsImage
  ports:
    - protocol: TCP
      port: 5000       # Exposed service port
      targetPort: 5000 # Matches containerPort in Deployment
      nodePort: 35000
  type: NodePort

  